/**
 * Web build wrapper: `expo export -p web`, then stamp the service worker with
 * the exact asset list from the finished build.
 *
 * Why this exists: Metro content-hashes the JS bundle and fonts, so their URLs
 * are only known after export. Without precaching them at SW install time the
 * app needs a *second* online visit before it works offline — the first visit
 * caches only the shell, because the service worker is not yet controlling the
 * page when those requests go out.
 */
import { execSync } from 'node:child_process';
import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { join, relative, posix, sep } from 'node:path';

const DIST = 'dist';

console.log('› expo export -p web');
execSync('npx expo export -p web --clear', { stdio: 'inherit' });

/** Every file in dist/, as root-relative URLs. */
async function walk(dir) {
  const out = [];
  for (const name of await readdir(dir)) {
    const full = join(dir, name);
    const s = await stat(full);
    if (s.isDirectory()) out.push(...(await walk(full)));
    else out.push('/' + relative(DIST, full).split(sep).join(posix.sep));
  }
  return out;
}

const all = await walk(DIST);

// Precache only what the shell needs to boot offline. @expo/vector-icons ships
// ~17 font families (~3.5 MB) but the app only renders Ionicons, so the rest
// are left to the runtime cache-on-demand path instead of bloating install.
const USED_FONTS = /Ionicons/;
const precache = all.filter((u) => {
  if (/\.map$/.test(u) || u === '/metadata.json' || u === '/sw.js') return false;
  if (/\.ttf$/.test(u)) return USED_FONTS.test(u);
  return true;
});

const skippedFonts = all.filter((u) => /\.ttf$/.test(u) && !USED_FONTS.test(u)).length;

// '/' is what a navigation to the bare origin requests; cache it as well as
// '/index.html' so an offline visit to the root resolves.
precache.unshift('/');

const swPath = join(DIST, 'sw.js');
let sw = await readFile(swPath, 'utf8');

// Cache version derived from the bundle hash, so each deploy invalidates the
// old cache instead of serving a stale mix of old and new chunks.
const bundle = precache.find((u) => /^\/_expo\/static\/js\/web\/.*\.js$/.test(u)) || '';
const version = (bundle.match(/index-([a-f0-9]+)\.js/) || [, 'dev'])[1].slice(0, 12);

const injected =
  `/* AUTO-GENERATED by scripts/build-web.mjs — do not edit. */\n` +
  `const CACHE = 'splitlocal-${version}';\n` +
  `const PRECACHE = ${JSON.stringify(precache, null, 2)};`;

// Swap the placeholder block for the generated one. Fail loudly rather than
// shipping a service worker that silently precaches nothing.
const BLOCK = /\/\* __BUILD_MANIFEST__[\s\S]*?__END_BUILD_MANIFEST__ \*\//;
if (!BLOCK.test(sw)) {
  console.error('\n✗ sw.js is missing the __BUILD_MANIFEST__ placeholder block.');
  process.exit(1);
}
sw = sw.replace(BLOCK, injected);

await writeFile(swPath, sw);

let bytes = 0;
for (const u of precache) {
  if (u === '/') continue; // an alias for index.html, not a file of its own
  // `u` is a root-relative URL ('/index.html'); strip the leading slash so it
  // resolves inside dist/ rather than at the filesystem root.
  bytes += (await stat(join(DIST, u.replace(/^\//, '')))).size;
}

console.log(
  `\n› sw.js stamped: cache "splitlocal-${version}"\n` +
    `  ${precache.length} files precached (${(bytes / 1024 / 1024).toFixed(2)} MB), ` +
    `${skippedFonts} unused icon fonts left to cache on demand`
);
for (const u of precache) console.log('   ' + u);
